class Config:
    BOT_TOKEN = "YOUR TELEGRAM BOT TOKEN HERE"
    WHITELIST = [1234567890, 0987654321] # Telegram users id
    ADMINLIST = [] # Just like in WHITELIST
    API_KEY = "YOUR OPENAI API KEY HERE"
    INSTRUCTIONS = "YOUR PROMPT HERE"
    MAX_CONTEXT_QUESTIONS = 5
    TEMPERATURE = 0.9
    MAX_TOKENS = 2048
    FREQUENCY_PENALTY = 0
    PRESENCE_PENALTY = 0.6