class Config:
    BOT_TOKEN = "YOUR TELEGRAM BOT TOKEN HERE"
    DB_NAME = "YOUR POSTGRESQL DB NAME HERE"
    DB_USER = "YOUR POSTGRESQL DB USER HERE"
    DB_PASS = "YOUR POSTGRESQL DB PASSWORD HERE"
    DB_HOST = "YOUR POSTGRESQL DB HOSTNAME HERE"
    DB_PORT = "YOUR POSTGRESQL DB PORT HERE"
    INSTRUCTIONS = "YOUR DEFAULT PROMPT HERE"
    MAX_CONTEXT_QUESTIONS = 10
    TEMPERATURE = 0.9
    MAX_TOKENS = 2048
    FREQUENCY_PENALTY = 0.9
    PRESENCE_PENALTY = 0.6