class Config:
    BOT_TOKEN = "YOUR TELEGRAM BOT TOKEN HERE"
    DB_NAME = "YOUR POSTGRESQL DB NAME HERE"
    DB_USER = "YOUR POSTGRESQL DB USER HERE"
    DB_PASS = "YOUR POSTGRESQL DB PASSWORD HERE"
    DB_HOST = "YOUR POSTGRESQL DB HOSTNAME HERE"
    DB_PORT = "YOUR POSTGRESQL DB PORT HERE"
    INSTRUCTIONS = "YOUR DEFAULT PROMPT HERE"
    MAX_CONTEXT_QUESTIONS = 10
    ADMIN_ID = 0  # YOUR TELEGRAM ID HERE, ONLY ONE IS POSSIBLE, YOU CAN ADD MORE IF YOU NEED FROM /admin
